### ISSUE TITLE
How to download Pre-trained model.

### ISSUE THREAD

**Issue by shankarj67** [titu1994/keras-SparseNet#2]
Hi,

Thank you for writing this Code.

Could you please tell me where to download the weight "**SparseNet-40-24-CIFAR10.h5**".

In your case, you are loading the weight but there is no folder called weights in this repo.

**Comment by maddy46** [comment]
Hello,

Even i am looking for the 'SparseNet-40-24-CIFAR10.h5'. weight file.
Did you get it?

**Comment by shankarj67** [comment]
Hi @maddy46,

I did not get the weight file.

I am waiting for an author to reply.

**Comment by titu1994** [comment]
There's some issue with the training of the model. I have tried both the PyTorch version from the authors code and mine but cant hit the accuracies stated in the papers, therefore I won't be posting the weights.
